name: shrine
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  # ❌ No pongas flutter_launcher_icons aquí

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4   # ✅ Solo aquí

# ✅ Bloque de configuración a nivel raíz (no dentro de "flutter:")
flutter_launcher_icons:
  android: "launcher_icon"           # Nombre del recurso que generará
  image_path: "assets/icons/momos.jpg" # Ruta al PNG/JPG cuadrado de tu icono
  # Opcional iOS:
  ios: true
  remove_alpha_ios: true
  # Opcional Android adaptive:
  adaptive_icon_background: "#FFFFFF" # o una imagen
  adaptive_icon_foreground: "assets/icons/momos.jpg"

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
  assets:
    - assets/
    - assets/shrine_images/
